pipeline {
    agent any

    parameters {
        string(defaultValue: "NAME", description: "What would you like to name this deployment?", name: "deployName")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Which AWS environment to deploy in?", name: "deployAWS")
        booleanParam(defaultValue: false, description: "Deployment confirmed?", name: "deployConfirmed")
    }

    stages {
        stage("Input"){
            steps{
                echo "string is set to: ${params.deployName}"
            }
        }
        stage("Choice"){
            steps{
                echo "string is set to: ${params.deployAWS}"
            }
        }
        stage("Checkbox"){
            steps{
                echo "booleanParam is set to: ${params.deployConfirmed}"
            }
        }
    }
}